travel/apps/cities/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    # path("", home, name="home"),
    path("cities", CityListView.as_view(), name="cities"),
    path("detail/<int:pk>/", CityDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", CityUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", CityDeleteView.as_view(), name="delete"),
    path("add/", CityCreateView.as_view(), name="create"),

]

travel/apps/trains/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    # path("", home, name="home"),
    path("", TrainListView.as_view(), name="home"),
    path("detail/<int:pk>/", TrainDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", TrainUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", TrainDeleteView.as_view(), name="delete"),
    path("add/", TrainCreateView.as_view(), name="create"),
]

travel/apps/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import home
from travel.apps.routes.views import RouteListView

urlpatterns = [
    path("", home, name="home"),

    # path("", include("travel.apps.cities.urls")),
    # path("", include("travel.apps.trains.urls")),

    # path("accounts/", include("travel.apps.accounts.urls"), name="accounts"),
    # path("find_routes/", find_routes, name="find_routes"),
    # path("add_route/", add_route, name="add_route"),
    # path("save_route/", save_route, name="save_route"),
    # path("list/", RouteListView.as_view(), name="list"),
    # path("detail/<int:pk>/", RouteDetailView.as_view(), name="detail"),
    # path("delete/<int:pk>/", RouteDeleteView.as_view(), name="delete"),
]

travel/urls.py
from django.contrib import admin
from django.urls import path, include

from travel.apps.routes.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cities/", include("travel.apps.cities.urls"),  name="cities"),
    path("trains/", include("travel.apps.trains.urls"), name="trains"),
    path("accounts/", include("travel.apps.accounts.urls"), name="accounts"),
    path("", home, name="home"),
    path("find_routes/", find_routes, name="find_routes"),
    path("add_route/", add_route, name="add_route"),
    path("save_route/", save_route, name="save_route"),
    path("list/", RouteListView.as_view(), name="list"),
    path("detail/<int:pk>/", RouteDetailView.as_view(), name="detail"),
    path("delete/<int:pk>/", RouteDeleteView.as_view(), name="delete"),
]

travel/apps/accounts/models.py
from django.db import models

# Create your models here.

travel/apps/cities/models.py
from django.db import models
from django.urls import reverse


class City(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Город')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('cities:detail', kwargs={'pk': self.pk})

travel/apps/routes/models.py
from django.db import models

from travel.apps.cities.models import City


class Route(models.Model):
    name = models.CharField(
        max_length=50, unique=True, verbose_name="Название маршрута"
    )
    travel_times = models.PositiveSmallIntegerField(
        verbose_name="Общее время в пути"
    )
    from_city = models.ForeignKey(
        City, on_delete=models.CASCADE,
        related_name="route_from_city_set",
        verbose_name="Из какого города"
    )
    to_city = models.ForeignKey(
        "cities.City", on_delete=models.CASCADE,
        related_name="route_to_city_set",
        verbose_name="В какой город"
    )
    trains = models.ManyToManyField(
        "trains.Train", verbose_name="Список поездов"
    )

    def __str__(self):
        return f"Маршрут {self.name} из города {self.from_city}"

    class Meta:
        verbose_name = "Маршрут"
        verbose_name_plural = "Маршруты"
        ordering = ["travel_times"]

travel/apps/cities/forms.py
from django import forms

from .models import City


class HtmlForm(forms.Form):
    name = forms.CharField(label='Город')


class CityForm(forms.ModelForm):
    name = forms.CharField(label='Город', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите название города'
    }))

    class Meta:
        model = City
        fields = ('name',)

travel/apps/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

from .forms import UserLoginForm, UserRegistrationForm


def login_view(request):
    form = UserLoginForm(request.POST or None)
    _next = request.GET.get("next")
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        _next = _next or "/"
        return redirect(_next)
    return render(request, "accounts/login.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("/")


def registration_view(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data["password"])
            new_user.save()
            return render(request, "accounts/register_done.html", {"new_user": new_user})
        return render(request, "accounts/register.html", {"form": form})
    else:
        form = UserRegistrationForm()
        return render(request, "accounts/register.html", {"form": form})

travel/apps/cities/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, \
    ListView
from django.views.generic import TemplateView

from .forms import HtmlForm, CityForm
from .models import City

__all__ = (
    "home", "CityDetailView", "CityCreateView", "CityUpdateView",
    "CityDeleteView", "CityListView"
)


def home(request, pk=None):
    if request.method == "POST":
        form = CityForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
    # if pk:
    # city = City.objects.filter(id=pk).first()
    # city = City.objects.get(id=pk)
    # city = get_object_or_404(City, id=pk)
    #
    # context = {"object": city}
    # return render(request, "cities/detail.html", context)
    form = CityForm()
    qs = City.objects.all()
    lst = Paginator(qs, 2)
    page_number = request.GET.get("page")
    page_obj = lst.get_page(page_number)
    context = {"page_obj": page_obj, "form": form}
    return render(request, "cities/home.html", context)


class CityDetailView(DetailView):
    queryset = City.objects.all()
    template_name = "cities/detail.html"


class CityCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = City
    form_class = CityForm
    template_name = "cities/create.html"
    success_url = reverse_lazy("cities:home")
    success_message = "Город успешно создан"


class CityUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = City
    form_class = CityForm
    template_name = "cities/update.html"
    success_url = reverse_lazy("cities:home")
    success_message = "Город успешно отредактирован"


class CityDeleteView(LoginRequiredMixin, DeleteView):
    model = City
    # template_name = "cities/delete.html"
    success_url = reverse_lazy("cities:home")

    def get(self, request, *args, **kwargs):
        messages.success(request, "Город успешно удален")
        return self.post(request, *args, **kwargs)


class CityListView(ListView):
    paginate_by = 2
    model = City
    template_name = "cities/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = CityForm()
        context["form"] = form
        return context

travel/apps/routes/admin.py
from django.contrib import admin

from travel.apps.routes.models import Route

admin.site.register(Route)

travel/apps/routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    name = 'routes'

travel/apps/routes/tests.py
from django.test import TestCase

# Create your tests here.

travel/apps/routes/utils.py
from travel.apps.trains.models import Train


def dfs_paths(graph, start, goal):
    """Функция поиска всех возможных маршрутов
    из одного города в другой. Вариант посещения
    одного и того же города более одного раза,
    не рассматривается.
    """
    stack = [(start, [start])]
    while stack:
        (vertex, path) = stack.pop()
        if vertex in graph.keys():
            for next_ in graph[vertex] - set(path):
                if next_ == goal:
                    yield path + [next_]
                else:
                    stack.append((next_, path + [next_]))


def get_graph(qs):
    graph = {}
    for q in qs:
        graph.setdefault(q.from_city_id, set())
        graph[q.from_city_id].add(q.to_city_id)
    return graph


def get_routes(request, form) -> dict:
    context = {'form': form}
    qs = Train.objects.all().select_related('from_city', 'to_city')
    graph = get_graph(qs)
    data = form.cleaned_data
    from_city = data['from_city']
    to_city = data['to_city']
    cities = data['cities']
    travelling_time = data['travelling_time']
    all_ways = list(dfs_paths(graph, from_city.id, to_city.id))
    if not len(all_ways):
        # нет ни одного маршрута для данного поиска
        raise ValueError('Маршрута, удовлетворяющего условиям не существует')
    if cities:
        # если есть города, через которые нужно проехать
        _cities = [city.id for city in cities]
        right_ways = []
        for route in all_ways:
            if all(city in route for city in _cities):
                right_ways.append(route)
        if not right_ways:
            # когда список маршрутов пуст
            raise ValueError('Маршрут, через эти города невозможен')
    else:
        right_ways = all_ways
    routes = []
    all_trains = {}
    for q in qs:
        all_trains.setdefault((q.from_city_id, q.to_city_id), [])
        all_trains[(q.from_city_id, q.to_city_id)].append(q)
    for route in right_ways:
        tmp = {}
        tmp['trains'] = []
        total_time = 0
        for i in range(len(route) - 1):
            qs = all_trains[(route[i], route[i + 1])]
            q = qs[0]
            total_time += q.travel_time
            tmp['trains'].append(q)
        tmp['total_time'] = total_time
        if total_time <= travelling_time:
            # если общее время в пути, меньше заданного,
            # то добавляем маршрут в общий список
            routes.append(tmp)
    if not routes:
        # если список пуст, то нет таких маршрутов,
        # которые удовлетворяли бы заданным условиям
        raise ValueError('Время в пути больше заданного')
    sorted_routes = []
    if len(routes) == 1:
        sorted_routes = routes
    else:
        times = list(set(r['total_time'] for r in routes))
        times = sorted(times)
        for time in times:
            for route in routes:
                if time == route['total_time']:
                    sorted_routes.append(route)
    context['routes'] = sorted_routes
    context['cities'] = {'from_city': from_city, 'to_city': to_city}
    return context

travel/apps/routes/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, DeleteView

from travel.apps.cities.models import City
from travel.apps.routes.forms import RouteForm, RouteModelForm
from travel.apps.routes.models import Route
from travel.apps.routes.utils import get_routes
from travel.apps.trains.models import Train


# @login_required
def home(request):
    form = RouteForm()
    return render(request, 'routes/home.html', {'form': form})


def find_routes(request):
    if request.method == "POST":
        form = RouteForm(request.POST)
        if form.is_valid():
            try:
                context = get_routes(request, form)
            except ValueError as e:
                messages.error(request, e)
                return render(request, 'routes/home.html', {'form': form})
            return render(request, 'routes/home.html', context)
        return render(request, 'routes/home.html', {'form': form})
    else:
        form = RouteForm()
        messages.error(request, "Нет данных для поиска")
        return render(request, 'routes/home.html', {'form': form})


def add_route(request):
    if request.method == "POST":
        context = {}
        data = request.POST
        if data:
            total_time = int(data['total_time'])
            from_city_id = int(data['from_city'])
            to_city_id = int(data['to_city'])
            trains = data['trains'].split(',')
            trains_lst = [int(t) for t in trains if t.isdigit()]
            qs = Train.objects.filter(id__in=trains_lst).select_related(
                'from_city', 'to_city')
            cities = City.objects.filter(
                id__in=[from_city_id, to_city_id]).in_bulk()
            form = RouteModelForm(
                initial={
                    'from_city': cities[from_city_id],
                    'to_city': cities[to_city_id],
                    'travel_times': total_time,
                    'trains': qs
                }
            )
            context['form'] = form
        return render(request, 'routes/create.html', context)
    else:
        messages.error(request, "Невозможно сохранить несуществующий маршрут")
        return redirect('/')


def save_route(request):
    if request.method == "POST":
        form = RouteModelForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Маршрут успешно сохранен")
            return redirect('/')
        return render(request, 'routes/create.html', {'form': form})
    else:
        messages.error(request, "Невозможно сохранить несуществующий маршрут")
        return redirect('/')


class RouteListView(ListView):
    paginate_by = 10
    model = Route
    template_name = 'routes/list.html'


class RouteDetailView(DetailView):
    queryset = Route.objects.all()
    template_name = 'routes/detail.html'


class RouteDeleteView(LoginRequiredMixin, DeleteView):
    model = Route
    success_url = reverse_lazy('home')

    def get(self, request, *args, **kwargs):
        messages.success(request, 'Маршрут успешно удален')
        return self.post(request, *args, **kwargs)

travel/apps/trains/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (
    DetailView, CreateView, UpdateView, DeleteView,
    ListView
)

from .forms import TrainForm
from .models import Train

__all__ = (
    "home", "TrainListView",
    "TrainDetailView",
    "TrainCreateView", "TrainUpdateView",
    "TrainDeleteView",
)


def home(request, pk=None):
    qs = Train.objects.all()
    lst = Paginator(qs, 5)
    page_number = request.GET.get("page")
    page_obj = lst.get_page(page_number)
    context = {"page_obj": page_obj, }
    return render(request, "trains/home.html", context)


class TrainListView(ListView):
    paginate_by = 10
    model = Train
    template_name = "trains/home.html"


class TrainDetailView(DetailView):
    queryset = Train.objects.all()
    template_name = "trains/detail.html"


class TrainCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Train
    form_class = TrainForm
    template_name = "trains/create.html"
    success_url = reverse_lazy("trains:home")
    success_message = "Поезд успешно создан"


class TrainUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Train
    form_class = TrainForm
    template_name = "trains/update.html"
    success_url = reverse_lazy("trains:home")
    success_message = "Поезд успешно отредактирован"


class TrainDeleteView(LoginRequiredMixin, DeleteView):
    model = Train
    # template_name = "trains/delete.html"
    success_url = reverse_lazy("trains:home")

    def get(self, request, *args, **kwargs):
        messages.success(request, "Поезд успешно удален")
        return self.post(request, *args, **kwargs)

travel/apps/views.py
from django.views.generic import TemplateView
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    name = "Bob"
    return render(request, "home.html", {"name": name})


def about(request):
    name = "About us"
    return render(request, "about.html", {"name": name})

travel/views.py
from django.views.generic import TemplateView
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    name = "Bob"
    # template_name = "home.html"
    return render(request, "home.html", {"name": name})


def about(request):
    name = "About us"
    return render(request, "about.html", {"name": name})

travel/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block content %}
    <h1> {{ name }}! </h1>
{% endblock %}

<h1>Hello world! </h1>

travel/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light container" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url "home" %}">FindRoute</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if request.path == cities_home_url %}active {% endif %}	">
                <a class="nav-link" href="{% url "home" %}">Города </a>
            </li>
            <li class="nav-item {% if request.path == trains_home_url %}active {% endif %}">
                <a class="nav-link" href="{% url "home" %}">Поезда</a>
            </li>
            <li class="nav-item {% if request.path == route_list %} active {% endif %}">
                <a class="nav-link" href="{% url "home" %}">Маршруты</a>
            </li>


        </ul>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto my-4">
            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger  alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% else %}
                        <div class="alert alert-success  alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

<div class="container">
    {% block content %}{% endblock %}
</div>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
-->
<script>
    $(document).ready(function () {
        $(".js-example-basic-single").select2();
        $(".js-example-basic-multiple").select2();
    });
</script>
</body>
</html>

travel/templates/form.html
<div class="row">
    <div class="col-md-4">
        <form action="{{ action }}" method="post"> {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary"> {{ button }}</button>
        </form>
    </div>
</div>

travel/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
    <h1> Hello {{ name }}! </h1>
{% endblock %}